#!/usr/bin/env python3
"""Re-anchor the links on Quartz folder pages that were built from a sibling note.

When a note has the same name as a folder next to it (Concepts.md beside Concepts/,
History.md beside History/), Quartz's FolderPage emitter uses that note as the
folder's index page and writes it a second time to <Folder>/index.html. Only the
asset paths of that copy are computed for the deeper location; everything derived
from the page itself -- breadcrumbs, the body, the listing of folder contents --
keeps the paths of the original page, so served from /Concepts/ each one resolves
a level too deep: /Concepts/Concepts/Sharding, /History/History/2026.32.

Every such link is off by exactly one level, so shift the root-relative ones down.
A folder page Quartz generated itself has no sibling <Folder>.html and is skipped;
compare against one (Articles/index.html) to see the shape this restores.
"""

import pathlib
import re
import sys

# ./foo -> ../foo, ./ -> ../, and the bare href="." the breadcrumb uses for Home.
SHIFT = re.compile(r'\b(href|src)="\.(/|")')


def fix_page(page: pathlib.Path) -> int:
    html = page.read_text(encoding="utf-8")
    fixed, count = SHIFT.subn(
        lambda m: f'{m.group(1)}="..{"/" if m.group(2) == "/" else chr(34)}', html
    )
    if count:
        page.write_text(fixed, encoding="utf-8")
    return count


def main() -> int:
    docs = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "docs")
    if not docs.is_dir():
        print(f"fix-folder-pages: {docs} is not a directory", file=sys.stderr)
        return 1

    total = 0
    for page in sorted(docs.rglob("*/index.html")):
        folder = page.parent
        if not folder.with_suffix(".html").exists():
            continue  # generated by Quartz, links already correct
        n = fix_page(page)
        total += n
        print(f"fix-folder-pages: {folder.name}/index.html — {n} links re-anchored")

    print(f"fix-folder-pages: {total} links re-anchored")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
